name: Upload to COS

on:
  push:
    branches:
      - master
 
jobs:
  upload-to-cos:
    name: Upload to Tencent Cloud COS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Upload to Tencent Cloud COS
        uses: renbaoshuo/upload-to-cos@beta-v2
        with:
          secret-id: ${{ secrets.TENCENT_CLOUD_SECRET_ID }}
          secret-key: ${{ secrets.TENCENT_CLOUD_SECRET_KEY }}
          bucket: ${{ secrets.COS_BUCKET }}
          region: ${{ secrets.COS_REGION }}
          local-path: public
          remote-path: ""
          incremental: true
